targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        generate_for:
          - lib/**/*.dart
      build_runner:build_runner:
        enabled: true

